return {
    Names={
        ["Arvyokyck"] = true,
        ["Batddys"] = true,
        ["Craooutkazdge"] = true,
        ["Killerfbg"] = true,
        ["Nohnohnnhonoh"] = true,
        ["Novasilex"] = true,
        ["Sknoneag"] = true,
        ["Sssyu"] = true,
        ["Tussiosi"] = true,
        ["Weaponclea"] = true,
    },
    Terms=T{
        "\x81i",
        "\x81\x99",
        "\x81\x9A",
        "1%-99",
        "Job Points.*2100",
        "Job Points.*500",
        "Job Points.*4m",
        "JP.*2100",
        "JP.*500",
        "Capacity Points.*2100",
        "Capacity Points.*500",
        "CPS*.*2100",
        "CPS*.*500",
        "\xEF\xBD\x86\xEF\xBD\x86\xEF\xBD\x98\xEF\xBD\x89\xEF\xBD\x93\xEF\xBD\x88\xEF\xBD\x8F\xEF\xBD\x90",
        "Jinpu 99999",
        "Jinpu99999",
        "This is IGXE",
        "Clear Mind*.*15mins rdy start",
        "Reisenjima*.*Helms*.*T4*.*Buy",
        "Aeonic Weapon*.*3zone*.*Buy",
        "Tumult Curator*.*Kill",
        "Aeonic Weapon*.*Mind",
        "Aeonic Weapon*.*Buy",
        "Selling Aeonic",
        "Empy Weapons Abyssea",
        "50 50 75",
    },
};