return T{
    Name = "Radix",
    Id = 838263,
    NPCs = T{
        ["Quntsu-Nointsu"] = 1775150462,
        ["Tamba-Namba"] = 1775162174,
        ["Bhio Fehriata"] = 1775148793,
        ["Zuah Lepahnyu"] = 1775151320,
        ["Willah Maratahya"] = 1775151596,
        ["Burute-Sorute"] = 1775510764,
        ["Moozo-Koozo"] = 1775637198,
        ["Tuh Almobankha"] = 1775151185,
        ["Yulon-Polon"] = 1775503155,
        ["Cattah Pamjah"] = 1775148528,
        ["Debadle-Levadle"] = 1775148993,
        ["Shupah Mujuuk"] = 1775150560,
        ["Styi Palneh"] = 1775150814,
        ["Eron-Tomaron"] = 1775149857,
        ["Aligi-Kufongi"] = 1775148657,
        ["Koyol-Futenol"] = 1775150088,
    },
    Titles = T{
        [1] = false, --Fodderchief Flayer
        [2] = true, --Warchief Wrecker
        [3] = true, --Dread Dragon Slayer
        [4] = false, --Overlord Executioner
        [5] = false, --Dark Dragon Slayer
        [6] = false, --Adamantking Killer
        [7] = false, --Black Dragon Slayer
        [8] = false, --Manifest Mauler
        [9] = true, --Behemoth's Bane
        [10] = true, --Archmage Assassin
        [11] = true, --Hellsbane
        [12] = false, --Giant Killer
        [13] = true, --Lich Banisher
        [14] = true, --Jellybane
        [15] = true, --Bogeydowner
        [16] = true, --Beakbender
        [17] = false, --Skullcrusher
        [18] = true, --Morbolbane
        [19] = true, --Goliath Killer
        [20] = false, --Mary's Guide
        [21] = true, --Simurgh Poacher
        [22] = true, --Roc Star
        [23] = true, --Serket Breaker
        [24] = true, --Cassienova
        [25] = false, --The Hornsplitter
        [26] = false, --Tortoise Torturer
        [27] = false, --Mon Cherry
        [28] = true, --Behemoth Dethroner
        [29] = false, --The Vivisector
        [30] = false, --Dragon Asher
        [31] = false, --Expeditionary Trooper
        [32] = true, --Bearer of the Wisewoman's Hope
        [33] = true, --Bearer of the Eight Prayers
        [34] = true, --Lightweaver
        [35] = true, --Destroyer of Antiquity
        [36] = true, --Sealer of the Portal of the Gods
        [37] = true, --Burier of the Illusion
        [39] = false, --Family Counselor
        [41] = true, --Great Grappler Scorpio!?
        [42] = true, --Bond Fixer
        [43] = true, --Vampire Hunter D-Minus
        [44] = true, --Sheep's Milk Deliverer
        [45] = false, --Bean Cuisine Salter
        [46] = true, --Total Loser
        [47] = true, --Doctor Shantotto's Flavor of the Month
        [48] = false, --Pilgrim to Holla
        [49] = false, --Pilgrim to Dem
        [50] = false, --Pilgrim to Mea
        [51] = false, --Daybreak Gambler
        [52] = false, --The Pious One
        [53] = false, --A Moss Kind Person
        [54] = false, --Entrance Denied
        [55] = false, --Apiarist
        [56] = false, --Rabbiter
        [57] = false, --Royal Grave Keeper
        [58] = false, --Courier Extraordinaire
        [59] = false, --Ronfaurian Rescuer
        [60] = false, --Pickpocket Pincher
        [61] = false, --Fang Finder
        [62] = false, --Faith like a Candle
        [63] = false, --The Pure One
        [64] = true, --Lost Child Officer
        [65] = false, --Silencer of the Lambs
        [66] = false, --Lost & Found Officer
        [67] = false, --Green Grocer
        [68] = false, --The Benevolent One
        [69] = true, --Knight in Training
        [70] = false, --Lizard Skinner
        [71] = false, --Bug Catcher
        [72] = false, --Spelunker
        [73] = true, --Arms Trader
        [74] = false, --Traveling Medicine Man
        [75] = false, --Cat Skinner
        [76] = false, --Carp Diem
        [77] = false, --Advertising Executive
        [78] = false, --Third-rate Organizer
        [79] = false, --Second-rate Organizer
        [80] = false, --First-rate Organizer
        [81] = false, --Bastok Welcoming Committee
        [82] = false, --Shell Outer
        [83] = false, --Bucket Fisher
        [84] = false, --Pursuer of the Past
        [85] = false, --Pursuer of the Truth
        [86] = true, --Mommy's Helper
        [87] = false, --Hot Dog
        [88] = false, --Stampeder
        [89] = false, --Qiji's Friend
        [90] = false, --Qiji's Rival
        [91] = false, --Contest Rigger
        [92] = false, --Ringbearer
        [93] = false, --Kulatz Bridge Companion
        [94] = false, --Beadeaux Surveyor
        [95] = false, --Avenger
        [96] = false, --Treasure Scavenger
        [97] = false, --Airship Denouncer
        [98] = false, --Zeruhn Sweeper
        [99] = true, --Tearjerker
        [100] = false, --Crab Crusher
        [101] = false, --Star of Ifrit
        [102] = false, --Sorrow Drowner
        [103] = false, --Brygid-approved
        [104] = false, --Drachenfall Ascetic
        [105] = true, --"Steaming Sheep" Regular
        [106] = false, --Purple Belt
        [107] = false, --Gustaberg Tourist
        [108] = false, --Sand Blaster
        [109] = false, --Black Death
        [111] = true, --Fresh "North Winds" Recruit
        [112] = true, --New "Best of the West" Recruit
        [113] = true, --New "Buuma's Boomers" Recruit
        [114] = true, --Heavens Tower Gatehouse Recruit
        [115] = true, --Cat Burglar Groupie
        [116] = true, --Crawler Culler
        [117] = false, --Savior of Knowledge
        [118] = true, --Star-ordained Warrior
        [119] = false, --Lower than the Lowest Tunnel Worm
        [120] = false, --Star Onion Brigade Member
        [121] = false, --Star Onion Brigadier
        [122] = false, --Quick Fixer
        [123] = false, --Fake-moustached Investigator
        [124] = false, --Hakkuru-Rinkuru's Benefactor
        [125] = false, --S.O.B. Super Hero
        [126] = false, --Editor's Hatchet Man
        [127] = false, --Doctor Shantotto's Guinea Pig
        [128] = false, --Spoilsport
        [129] = false, --Super Model
        [130] = true, --Ghostie Buster
        [131] = false, --Night Sky Navigator
        [132] = true, --Fast Food Deliverer
        [133] = true, --Cupid's Florist
        [134] = true, --Tarutaru Murder Suspect
        [135] = true, --Hexer Vexer
        [136] = false, --Cardian Tutor
        [137] = false, --Deliverer of Tearful News
        [138] = true, --Fossilized Sea Farer
        [139] = false, --Down Piper Pipe-upperer
        [140] = true, --Kisser Make-upper
        [141] = false, --Timekeeper
        [142] = false, --Fortune-teller in Training
        [143] = false, --Torchbearer
        [144] = true, --Tenshodo Member
        [145] = true, --Chocobo Trainer
        [146] = false, --Bringer of Bliss
        [147] = false, --Activist for Kindness
        [148] = false, --Envoy to the North
        [149] = false, --Exorcist in Training
        [150] = false, --Professional Loafer
        [151] = false, --Clock Tower Preservationist
        [152] = false, --Life Saver
        [153] = false, --Fool's Errand Runner
        [154] = false, --Card Collector
        [155] = true, --Researcher of Classics
        [156] = false, --Street Sweeper
        [157] = false, --Mercy Errand Runner
        [158] = false, --Two's Company
        [159] = false, --Believer of Altana
        [160] = false, --Trader of Mysteries
        [161] = false, --Trader of Antiquities
        [162] = false, --Trader of Renown
        [163] = false, --Brown Belt
        [164] = true, --Horizon Breaker
        [165] = false, --Goblin's Exclusive Fashion Mannequin
        [166] = true, --Summit Breaker
        [167] = true, --Sky Breaker
        [168] = true, --Cloud Breaker
        [169] = true, --Star Breaker
        [170] = true, --Greedalox
        [171] = true, --Certified Rhinostery Venturer
        [172] = false, --Cordon Bleu Fisher
        [173] = false, --Ace Angler
        [174] = false, --Lu Shang-like Fisher King
        [176] = false, --Ecologist
        [177] = false, --Li'l Cupid
        [178] = false, --The Love Doctor
        [179] = false, --Savior of Love
        [180] = false, --Honorary Citizen of Selbina
        [181] = false, --Purveyor in Training
        [182] = false, --One-star Purveyor
        [183] = false, --Two-star Purveyor
        [184] = false, --Three-star Purveyor
        [185] = false, --Four-star Purveyor
        [186] = false, --Five-star Purveyor
        [187] = false, --Doctor Yoran-Oran Supporter
        [188] = false, --Doctor Shantotto Supporter
        [189] = false, --Professor Koru-Moru Supporter
        [190] = true, --Rainbow Weaver
        [191] = true, --Shadow Walker
        [192] = true, --Heir to the Holy Crest
        [193] = false, --Bushido Blade
        [195] = false, --Paragon of Paladin Excellence
        [196] = false, --Paragon of Beastmaster Excellence
        [197] = false, --Paragon of Ranger Excellence
        [198] = false, --Paragon of Dark Knight Excellence
        [199] = false, --Paragon of Bard Excellence
        [200] = false, --Paragon of Samurai Excellence
        [201] = false, --Paragon of Dragoon Excellence
        [202] = false, --Paragon of Ninja Excellence
        [203] = false, --Paragon of Summoner Excellence
        [206] = true, --New Adventurer
        [207] = false, --Certified Adventurer
        [208] = false, --Shadow Banisher
        [209] = false, --Tried and Tested Knight
        [210] = true, --Dark Sider
        [211] = false, --The Fanged One
        [212] = true, --Have Wings, Will Fly
        [213] = false, --Animal Trainer
        [214] = true, --Wandering Minstrel
        [215] = true, --Mog's Master
        [216] = true, --Mog's Kind Master
        [217] = true, --Mog's Exceptionally Kind Master
        [218] = false, --Paragon of Warrior Excellence
        [219] = false, --Paragon of Monk Excellence
        [220] = false, --Paragon of Red Mage Excellence
        [221] = false, --Paragon of Thief Excellence
        [222] = false, --Paragon of Black Mage Excellence
        [223] = false, --Paragon of White Mage Excellence
        [224] = true, --Mog's Loving Master
        [226] = false, --Royal Archer
        [227] = false, --Royal Spearman
        [228] = false, --Royal Squire
        [229] = false, --Royal Swordsman
        [230] = false, --Royal Cavalier
        [231] = false, --Royal Guard
        [232] = false, --Grand Knight of the Realm
        [233] = false, --Grand Temple Knight
        [234] = false, --Reserve Knight Captain
        [235] = false, --Elite Royal Guard
        [236] = false, --Legionnaire
        [237] = false, --Decurion
        [238] = false, --Centurion
        [239] = false, --Junior Musketeer
        [240] = false, --Senior Musketeer
        [241] = false, --Musketeer Commander
        [242] = false, --Gold Musketeer
        [243] = false, --Praefectus
        [244] = false, --Senior Gold Musketeer
        [245] = false, --Praefectus Castrorum
        [246] = true, --Freesword
        [247] = true, --Mercenary
        [248] = true, --Mercenary Captain
        [249] = true, --Combat Caster
        [250] = true, --Tactician Magician
        [251] = true, --Wise Wizard
        [252] = true, --Patriarch Protector
        [253] = true, --Caster Captain
        [254] = true, --Master Caster
        [255] = false, --Mercenary Major
        [256] = true, --Fugitive Minister Bounty Hunter
        [257] = false, --King of the Opo-opos
        [258] = false, --Excommunicate of Kazham
        [259] = false, --Kazham Caller
        [260] = false, --Dream Dweller
        [261] = false, --Apprentice Sommelier
        [262] = false, --Desert Hunter
        [263] = false, --Seeker of Truth
        [264] = false, --Kuftal Tourist
        [265] = false, --The Immortal Fisher, Lu Shang
        [266] = false, --Looks Sublime in a Subligar
        [267] = false, --Looks Good in Leggings
        [268] = false, --Honorary Doctorate, Majoring in Tonberries
        [269] = false, --Treasure-house Ransacker
        [270] = false, --Cracker of the Secret Code
        [271] = false, --Black Marketeer
        [272] = false, --Acquirer of Ancient Arcanum
        [273] = false, --Ya Done Good
        [274] = true, --Heir of the Great Fire
        [275] = true, --Heir of the Great Earth
        [276] = true, --Heir of the Great Water
        [277] = true, --Heir of the Great Wind
        [278] = true, --Heir of the Great Ice
        [279] = true, --Heir of the Great Lightning
        [280] = false, --Guider of Souls to the Sanctuary
        [281] = false, --Bearer of Bonds Beyond Time
        [282] = false, --Friend of the Opo-opos
        [283] = true, --Hero on Behalf of Windurst
        [284] = true, --Victor of the Balga Contest
        [285] = false, --Gullible's Travels
        [286] = false, --Even More Gullible's Travels
        [287] = true, --Heir of the New Moon
        [288] = false, --Assassin Reject
        [289] = false, --Black Belt
        [290] = false, --Vermillion Venturer
        [291] = false, --Cerulean Soldier
        [292] = false, --Emerald Exterminator
        [293] = true, --Guiding Star
        [294] = true, --Vestal Chamberlain
        [295] = false, --San d'Orian Royal Heir
        [296] = false, --Hero Among Heroes
        [297] = true, --Dynamis-San d'Oria Interloper
        [298] = true, --Dynamis-Bastok Interloper
        [299] = true, --Dynamis-Windurst Interloper
        [300] = true, --Dynamis-Jeuno Interloper
        [301] = true, --Dynamis-Beaucedine Interloper
        [302] = true, --Dynamis-Xarcabard Interloper
        [303] = false, --Discerning Individual
        [304] = false, --Very Discerning Individual
        [305] = false, --Extremely Discerning Individual
        [306] = false, --Royal Wedding Planner
        [307] = false, --Consort Candidate
        [308] = false, --Obsidian Storm
        [309] = false, --Pentacide Perpetrator
        [310] = false, --Wood Worshiper
        [311] = false, --Lumber Lather
        [312] = false, --Accomplished Carpenter
        [313] = false, --Anvil Advocate
        [314] = false, --Forge Fanatic
        [315] = false, --Accomplished Blacksmith
        [316] = false, --Trinket Turner
        [317] = false, --Silver Smelter
        [318] = false, --Accomplished Goldsmith
        [319] = false, --Knitting Know-It-All
        [320] = false, --Loom Lunatic
        [321] = false, --Accomplished Weaver
        [322] = false, --Formula Fiddler
        [323] = false, --Potion Potentate
        [324] = false, --Accomplished Alchemist
        [325] = false, --Bone Beautifier
        [326] = false, --Shell Scrimshander
        [327] = false, --Accomplished Boneworker
        [328] = false, --Hide Handler
        [329] = false, --Leather Lauder
        [330] = false, --Accomplished Tanner
        [331] = false, --Fastriver Fisher
        [332] = false, --Coastline Caster
        [333] = false, --Accomplished Angler
        [334] = false, --Gourmand Gratifier
        [335] = false, --Banquet Bestower
        [336] = false, --Accomplished Chef
        [337] = false, --Fine Tuner
        [338] = false, --Friend of the Helmed
        [339] = true, --Tavnazian Squire
        [340] = false, --Ducal Dupe
        [341] = false, --Hyper Ultra Sonic Adventurer
        [342] = false, --Rod Retriever
        [343] = false, --Deed Verifier
        [344] = false, --Chocobo Love Guru
        [345] = false, --Pick-up Artist
        [346] = false, --Trash Collector
        [347] = true, --Ancient Flame Follower
        [348] = true, --Tavnazian Traveler
        [349] = true, --Transient Dreamer
        [350] = true, --The Lost One
        [351] = true, --Treader of an Icy Past
        [352] = true, --Branded by Lightning
        [353] = true, --Seeker of the Light
        [354] = true, --Dead Body
        [355] = true, --Frozen Dead Body
        [356] = true, --Dreambreaker
        [357] = true, --Mist Melter
        [358] = true, --Delta Enforcer
        [359] = true, --Omega Ostracizer
        [360] = true, --Ultima Undertaker
        [361] = true, --Ulmia's Soulmate
        [362] = true, --Tenzen's Ally
        [363] = true, --Companion of Louverance
        [364] = true, --True Companion of Louverance
        [365] = true, --Prishe's Buddy
        [366] = true, --Nag'molada's Underling
        [367] = true, --Esha'ntarl's Comrade in Arms
        [368] = true, --The Chebukkis' Worst Nightmare
        [369] = false, --Brown Mage Guinea Pig
        [370] = false, --Brown Magic By-Product
        [371] = false, --Bastok's Second Best Dressed
        [372] = false, --Rookie Hero Instructor
        [373] = false, --Goblin in Disguise
        [374] = false, --Apostate for Hire
        [375] = false, --Talks with Tonberries
        [376] = false, --Rook Buster
        [377] = false, --Banneret
        [378] = false, --Gold BalliÅôÅôÅôÅôstar
        [379] = false, --Mythril BalliÅôÅôÅôstar
        [380] = false, --Silver BalliÅôÅôstar
        [381] = false, --Bronze BalliÅôstar
        [382] = false, --SearingÅöStar
        [383] = false, --StrikingÅöStar
        [384] = false, --SoothingÅöStar
        [385] = false, --SableÅöStar
        [386] = false, --ScarletÅöStar
        [387] = false, --SonicÅöStar
        [388] = false, --SaintlyÅöStar
        [389] = false, --ShadowyÅöStar
        [390] = false, --SavageÅöStar
        [391] = false, --SingingÅöStar
        [392] = false, --SnipingÅöStar
        [393] = false, --SlicingÅöStar
        [394] = false, --SneakingÅöStar
        [395] = false, --SpearingÅöStar
        [396] = false, --SummoningÅöStar
        [397] = false, --Putrid Purveyor of Pungent Petals
        [398] = true, --Unquenchable Light
        [399] = false, --Ballistager
        [400] = false, --Ultimate Champion of the World
        [401] = true, --Warrior of the Crystal
        [402] = false, --Indomitable Fisher
        [403] = true, --Averter of the Apocalypse
        [404] = true, --Banisher of Emptiness
        [409] = false, --Final BalliÅôÅôÅôÅôstar
        [410] = false, --BalliÅôÅôÅôÅôstar Royale
        [411] = false, --Destined Fellow
        [412] = false, --Orcish Serjeant
        [413] = false, --Bronze Quadav
        [414] = false, --Yagudo Initiate
        [415] = false, --Moblin Kinsman
        [416] = true, --Sin Hunter Hunter
        [417] = true, --Disciple of Justice
        [418] = false, --Monarch Linn Patrol Guard
        [419] = false, --Team Player
        [420] = false, --Worthy of Trust
        [421] = true, --Conqueror of Fate
        [422] = true, --Breaker of the Chains
        [423] = false, --A Friend Indeed
        [424] = true, --Heir to the Realm of Dreams
        [425] = false, --Gold Hook
        [426] = false, --Mythril Hook
        [427] = false, --Silver Hook
        [428] = false, --Copper Hook
        [430] = true, --Dynamis-Valkurm Interloper
        [431] = true, --Dynamis-Buburimu Interloper
        [432] = true, --Dynamis-Qufim Interloper
        [433] = true, --Dynamis-Tavnazia Interloper
        [434] = true, --Confronter of Nightmares
        [435] = false, --Disturber of Slumber
        [436] = false, --Interrupter of Dreams
        [437] = false, --SapphireÅöStar
        [438] = false, --SurgingÅöStar
        [439] = false, --SwayingÅöStar
        [440] = false, --Dark Resistant
        [441] = false, --Bearer of the Mark of Zahak
        [442] = false, --Seagull Phratrie Crew Member
        [443] = false, --Proud Automaton Owner
        [444] = true, --Private Second Class
        [445] = false, --Private First Class
        [446] = false, --Superior Private
        [447] = false, --Wildcat Publicist
        [448] = false, --Adamantking Usurper
        [449] = false, --Overlord Overthrower
        [450] = false, --Deity Debunker
        [451] = false, --Fafnir Slayer
        [452] = false, --Aspidochelone Sinker
        [453] = false, --Nidhogg Slayer
        [454] = true, --Maat Masher
        [455] = false, --Kirin Captivator
        [456] = false, --Cactrot Desacelerador
        [457] = true, --Lifter of Shadows
        [458] = false, --Tiamat Trouncer
        [459] = false, --Vrtra Vanquisher
        [460] = false, --World Serpent Slayer
        [461] = false, --Xolotl Xtrapolator
        [462] = false, --Boroka Beleaguerer
        [463] = false, --Ouryu Overwhelmer
        [464] = false, --Vinegar Evaporator
        [465] = false, --Virtuous Saint
        [466] = false, --Bye-bye, Taisai
        [467] = true, --Temenos Liberator
        [468] = true, --Apollyon Ravager
        [469] = false, --Wyrm Astonisher
        [470] = true, --Nightmare Awakener
        [471] = false, --Cerberus Muzzler
        [472] = false, --Hydra Headhunter
        [473] = false, --Shining Scale Rifler
        [474] = false, --Troll Subjugator
        [475] = false, --Gorgonstone Sunderer
        [476] = false, --Khimaira Carver
        [477] = false, --Elite Einherjar
        [478] = false, --Star Charioteer
        [479] = false, --Sun Charioteer
        [480] = false, --Subduer of the Mamool Ja
        [481] = false, --Subduer of the Trolls
        [482] = false, --Subduer of the Undead Swarm
        [483] = true, --Agent of the Allied Forces
        [484] = false, --Scenic Snapshotter
        [485] = false, --Branded by the Five Serpents
        [486] = false, --Immortal Lion
        [487] = false, --Paragon of Blue Mage Excellence
        [488] = false, --Paragon of Corsair Excellence
        [489] = false, --Paragon of Puppetmaster Excellence
        [490] = false, --Lance Corporal
        [491] = false, --Corporal
        [492] = false, --Master of Ambition
        [493] = false, --Master of Chance
        [494] = false, --Master of Manipulation
        [495] = true, --Ovjang's Errand Runner
        [496] = false, --Sergeant
        [497] = false, --Sergeant Major
        [498] = true, --Karababa's Tour Guide
        [499] = true, --Karababa's Bodyguard
        [500] = true, --Karababa's Secret Agent
        [501] = true, --Skyserpent Aggrandizer
        [502] = false, --Chief Sergeant
        [503] = true, --Aphmau's Mercenary
        [504] = true, --Nashmeira's Mercenary
        [505] = false, --Chocorookie
        [506] = false, --Second Lieutenant
        [507] = true, --Galeserpent Guardian
        [508] = true, --Stoneserpent Shocktrooper
        [509] = false, --Photopticator Operator
        [510] = true, --Salaheem's Risk Assessor
        [511] = true, --Treasure Trove Tender
        [512] = true, --Gessho's Mercy
        [513] = true, --Emissary of the Empress
        [514] = true, --Endymion Paratrooper
        [515] = true, --Naja's Comrade-In-Arms
        [516] = true, --Nashmeira's Loyalist
        [517] = true, --Preventer of Ragnarok
        [518] = true, --Champion of Aht Urhgan
        [519] = false, --First Lieutenant
        [520] = false, --Captain
        [521] = false, --Crystal Stakes Cupholder
        [522] = false, --Winning Owner
        [523] = false, --Victorious Owner
        [524] = false, --Triumphant Owner
        [525] = false, --High Roller
        [526] = false, --Fortune's Favorite
        [527] = false, --Superhero
        [528] = false, --Superheroine
        [529] = true, --Bloody Berserker
        [530] = false, --The Sixth Serpent
        [531] = true, --Eternal Mercenary
        [532] = true, --Springserpent Sentry
        [533] = false, --SprightlyÅöStar
        [534] = false, --SagaciousÅöStar
        [535] = false, --Schultz Scholar
        [536] = false, --Knight of the Iron Ram
        [537] = true, --Fourth Division Soldier
        [538] = false, --Cobra Unit Mercenary
        [539] = false, --Windtalker
        [540] = false, --Lady Killer
        [541] = false, --Troupe Brilioth Dancer
        [542] = true, --Cait Sith's Assistant
        [543] = false, --Ajido-Marujido's Minder
        [544] = false, --Comet Charioteer
        [545] = false, --Moon Charioteer
        [546] = false, --Sandworm Wrangler
        [547] = false, --Ixion Hornbreaker
        [548] = false, --Lambton Worm Desegmenter
        [549] = false, --Pandemonium Queller
        [550] = false, --Debaser of Dynasties
        [551] = false, --Disperser of Darkness
        [552] = false, --Ender of Idolatry
        [553] = false, --Lugh Exorcist
        [554] = false, --Elatha Exorcist
        [555] = false, --Ethniu Exorcist
        [556] = false, --Tethra Exorcist
        [557] = false, --Buarainech Exorcist
        [558] = false, --Oupire Impaler
        [559] = false, --Scylla Skinner
        [560] = false, --Zirnitra Wingclipper
        [561] = false, --Dawon Trapper
        [562] = false, --Krabkatoa Steamer
        [563] = false, --Orcus Trophy Hunter
        [564] = false, --Blobdingnag Burster
        [565] = false, --Verthandi Ensnarer
        [566] = false, --Ruthven Entomber
        [567] = false, --Yilbegan Hideflayer
        [568] = true, --Torchbearer of the 1st Walk
        [569] = true, --Torchbearer of the 2nd Walk
        [570] = true, --Torchbearer of the 3rd Walk
        [571] = true, --Torchbearer of the 4th Walk
        [572] = true, --Torchbearer of the 5th Walk
        [573] = true, --Torchbearer of the 6th Walk
        [574] = true, --Torchbearer of the 7th Walk
        [575] = true, --Torchbearer of the 8th Walk
        [576] = false, --Furniture Store Owner
        [577] = false, --Armory Owner
        [578] = false, --Jewelry Store Owner
        [579] = false, --Boutique Owner
        [580] = false, --Apothecary Owner
        [581] = false, --Curiosity Shop Owner
        [582] = false, --Shoeshop Owner
        [583] = false, --Fishmonger Owner
        [584] = false, --Restaurant Owner
        [585] = true, --Assistant Detective
        [586] = false, --Promising Dancer
        [587] = false, --Stardust Dancer
        [588] = false, --Elegant Dancer
        [589] = false, --Dazzling Dance Diva
        [590] = false, --Friend of Lehko Habhoka
        [591] = false, --Summa Cum Laude
        [592] = false, --Grimoire Bearer
        [593] = false, --Seasoning Connoisseur
        [594] = false, --Fine Young Griffon
        [595] = false, --Babban's Traveling Companion
        [596] = false, --Fellow Fortifier
        [597] = false, --Chocochampion
        [598] = true, --Traverser of Time
        [599] = true, --Mythril Musketeer No. 6
        [600] = false, --Jewel of the Cobra Unit
        [601] = false, --Knight of the Swiftwing Griffin
        [602] = false, --Wyrmsworn Protector
        [603] = true, --Flameserpent Facilitator
        [609] = false, --Swarminator
        [610] = true, --Battle of Jeuno Veteran
        [611] = true, --Grand Greedalox
        [612] = false, --Karaha-Baruha's Research Assistant
        [613] = false, --Honorary Knight of the Cardinal Stag
        [614] = true, --Detector of Deception
        [615] = false, --Silencer of the Echo
        [616] = true, --Bestrider of Futures
        [617] = false, --Mog House Handyperson
        [618] = true, --Presidential Protector
        [619] = false, --The Moon's Companion
        [620] = false, --Arrester of the Ascension
        [621] = false, --House Aurchiat Retainer
        [622] = true, --Wanderer of Time
        [623] = false, --Smiter of the Shadow
        [624] = true, --Heir of the Blessed Radiance
        [625] = true, --Heir of the Blighted Gloom
        [626] = true, --Sworn to the Dark Divinity
        [627] = true, --Temperer of Mythril
        [628] = false, --Star in the Azure Sky
        [629] = false, --Fangmonger Forestaller
        [630] = false, --Visitor to Abyssea
        [631] = false, --Friend of Abyssea
        [632] = false, --Warrior of Abyssea
        [633] = false, --Stormer of Abyssea
        [634] = false, --Devastator of Abyssea
        [635] = false, --Hero of Abyssea
        [636] = false, --Champion of Abyssea
        [637] = false, --Conqueror of Abyssea
        [638] = false, --Savior of Abyssea
        [639] = true, --Vanquisher of Spite
        [640] = false, --Hadhayosh Halterer
        [641] = true, --Briareus Feller
        [642] = false, --Karkinos Clawcrusher
        [643] = false, --Carabosse Quasher
        [644] = true, --Ovni Obliterator
        [645] = false, --Ruminator Confounder
        [646] = false, --Eccentricity Expunger
        [647] = false, --Fistule Drainer
        [648] = true, --Kukulkan Defanger
        [649] = true, --Turul Grounder
        [650] = false, --Bloodeye Banisher
        [651] = false, --Satiator Depriver
        [652] = true, --Iratham Capturer
        [653] = false, --Lacovie Capsizer
        [654] = false, --Chloris Uprooter
        [655] = false, --Myrmecoleon Tamer
        [656] = true, --Glavoid Stampeder
        [657] = false, --Usurper Deposer
        [658] = true, --Yaanei Crasher
        [659] = true, --Kutharei Unhorser
        [660] = true, --Sippoy Capturer
        [661] = false, --Titlacauan Dismemberer
        [662] = false, --Smok Defogger
        [663] = false, --Amhuluk Inundater
        [664] = false, --Pulverizer Dismantler
        [665] = false, --Durinn Deceiver
        [666] = false, --Karkadann Exoculator
        [667] = false, --Ulhuadshi Desiccator
        [668] = true, --Itzpapalotl Declawer
        [669] = false, --Sobek Mummifier
        [670] = true, --Cirein-croin Harpooner
        [671] = false, --Bukhis Tetherer
        [672] = true, --Sedna Tuskbreaker
        [673] = true, --Cleaver Dismantler
        [674] = false, --Executioner Dismantler
        [675] = false, --Severer Dismantler
        [676] = false, --Lusca Debunker
        [677] = false, --Tristitia Deliverer
        [678] = false, --Ketea Beacher
        [679] = true, --Rani Decrowner
        [680] = false, --Orthrus Decapitator
        [681] = true, --Dragua Slayer
        [682] = true, --Bennu Deplumer
        [683] = false, --Hedjedjet Destinger
        [684] = false, --Cuijatender Desiccator
        [685] = false, --Brulo Extinguisher
        [686] = false, --Pantokrator Disprover
        [687] = false, --Apademak Annihilator
        [688] = false, --Isgebind Defroster
        [689] = true, --Resheph Eradicator
        [690] = false, --Empousa Expurgator
        [691] = false, --Indrik Immolator
        [692] = false, --Ogopogo Overturner
        [693] = true, --Raja Regicide
        [694] = false, --Alfard Detoxifier
        [695] = false, --Azdaja Abolisher
        [696] = true, --Amphitrite Shucker
        [697] = false, --Fuath Purifier
        [698] = false, --Killakriq Excoriator
        [699] = false, --Maere Bestirrer
        [700] = true, --Wyrm God Defier
        [701] = true, --Hahava Condemner
        [702] = true, --Celaeno Silencer
        [703] = true, --Voidwrought Deconstructor
        [704] = false, --Devourer of Shadows
        [705] = true, --Kaggen Clobberer
        [706] = true, --Akvan Absterger
        [707] = true, --Pil Unfrocker
        [708] = true, --Qilin Contravener
        [709] = true, --Uptala Reprobator
        [710] = true, --Aello Abator
        [711] = true, --Torchbearer of the 9th Walk
        [712] = true, --Torchbearer of the 10th Walk
        [713] = true, --Torchbearer of the 11th Walk
        [714] = false, --Nightmare Illuminator
        [715] = true, --Gaunab Gutter
        [716] = true, --Kalasutrax Cremator
        [717] = true, --Ocythoe Overrider
        [718] = true, --Ig-Alima Inhumer
        [719] = true, --Botulus Rex Engorger
        [720] = true, --Torchbearer of the 12th Walk
        [721] = true, --Torchbearer of the 13th Walk
        [722] = true, --Torchbearer of the 14th Walk
        [723] = true, --Torchbearer of the 15th Walk
        [724] = false, --Delver of the Depths
        [725] = false, --Subjugator of the Lofty
        [726] = false, --Subjugator of the Mired
        [727] = false, --Subjugator of the Soaring
        [728] = false, --Subjugator of the Veiled
        [729] = false, --Legendary Legionnaire
        [730] = true, --Witness to Provenance
        [731] = true, --Bismarck Flenser
        [732] = true, --Morta Extirpator
        [733] = false, --Unsung Heroine
        [734] = false, --Epic Heroine
        [735] = false, --Epic Einherjar
        [736] = true, --Mender of Wings
        [737] = false, --Champion of the Dawn
        [738] = true, --Bushin Aspirant
        [739] = true, --Bushin-Ryu Inheritor
        [740] = true, --Temenos Emancipator
        [741] = true, --Apollyon Razer
        [742] = false, --Goldwing Squasher
        [743] = false, --Silagilith Detonator
        [744] = false, --Surtr Smotherer
        [745] = false, --Dreyruk Predominator
        [746] = false, --Samursk Vitiator
        [747] = false, --Umagrhk Manemangler
        [748] = false, --Supernal Savant
        [749] = false, --Solar Sage
        [750] = false, --Bolide Baron
        [751] = false, --Moon Maven
        [752] = false, --Izyx Vexer
        [753] = false, --Grannus Garroter
        [754] = false, --Svaha Striker
        [755] = false, --Melisseus Domesticator
        [756] = false, --Waterway Exemplar
        [757] = false, --Cavern Exemplar
        [758] = true, --Muyingwa Wingcrusher
        [759] = true, --Dakuwaqa Trawler
        [760] = true, --Tojil Douser
        [761] = true, --Colkhab Dethroner
        [762] = true, --Achuka Glaciator
        [763] = true, --Tchakka Desiccator
        [764] = false, --Weald Exemplar
        [765] = true, --Hurkan Birdlimeist
        [766] = true, --Yumcax Logger
        [767] = true, --Colkhab Hivecrusher
        [768] = true, --Achuka Coagulator
        [769] = true, --Tchakka Filleter
        [770] = false, --Rabbit Tussler
        [771] = false, --Helminth Mincer
        [772] = false, --Mandragardener
        [773] = false, --Moppet Massacrer
        [774] = false, --Rip-roaring Limbrender
        [775] = false, --Shell Shocker
        [776] = false, --Yagudo Coopkeeper
        [777] = false, --Gigasplosion Expert
        [778] = false, --Brother-in-arms
        [779] = false, --Antica Hunter
        [780] = false, --Amphibian Adulterator
        [781] = false, --Tonberry Toppler
        [782] = false, --Bloodline Corrupter
        [783] = true, --Kumhau Roaster
        [784] = false, --Brilliance Manifest
        [785] = false, --Quieter of Ancient Thoughts
        [786] = false, --Ark Hume Humiliator
        [787] = false, --Ark Elvaan Eviscerator
        [788] = false, --Ark Mithra Maligner
        [789] = false, --Ark Tarutaru Trouncer
        [790] = false, --Ark Galka Gouger
        [791] = false, --Pentarch Pacifier
        [792] = false, --Dream Distiller
        [793] = false, --Ra'Kaznar Exemplar
        [794] = true, --Utkux Peltburner
        [795] = true, --Cailimh Plumageplucker
        [796] = true, --Wopket Trunksplitter
        [797] = false, --Ouryu Obfuscator
        [798] = false, --Unwavering Blaze
        [799] = false, --Lancelord Divester
        [800] = false, --Gessho Pinioner
        [801] = false, --Sin Purger
        [802] = false, --Adumbration Disperser
        [803] = false, --Queller of Otherworldly Gales
        [804] = false, --Blaze Marshaller
        [805] = false, --Penitentes Blaster
        [806] = false, --Sirocco Tamer
        [807] = false, --Suchian Feller
        [808] = false, --Ombifid Slayer
        [809] = false, --Nilotican Decimator
        [810] = false, --Illuminator of the 1st Walk
        [811] = false, --Illuminator of the 2nd Walk
        [812] = true, --Illuminator of the 3rd Walk
        [813] = true, --Illuminator of the 4th Walk
        [814] = false, --Illuminator of the 5th Walk
        [815] = false, --Illuminator of the 6th Walk
        [816] = false, --Illuminator of the 7th Walk
        [817] = false, --Illuminator of the 8th Walk
        [818] = false, --Illuminator of the 9th Walk
        [819] = false, --Illuminator of the 10th Walk
        [820] = false, --Illuminator of the 11th Walk
        [821] = false, --Illuminator of the 12th Walk
        [822] = true, --Illuminator of the 13th Walk
        [823] = false, --Illuminator of the 14th Walk
        [824] = false, --Illuminator of the 15th Walk
        [825] = false, --Lithosphere Annihilator
        [826] = false, --Fulmination Disruptor
        [827] = false, --Bore Repulsor
        [828] = true, --Palloritus Punisher
        [829] = true, --Putraxia Pulverizer
        [830] = true, --Rancibus Ravager
        [831] = false, --Alluvion Assailant
        [832] = true, --Perfidien Paindealer
        [833] = true, --Plouton Pincer
        [834] = false, --Fleetstalker Fileter
        [835] = false, --Shockmaw Subjugator
        [836] = true, --Geodancer
        [837] = true, --Runic Engraver
        [838] = true, --Apprentice Tarutaru Sauce Manager
        [839] = true, --Vegetable Revolutionary
        [840] = true, --Friend to Gluttons
        [841] = true, --Waypoint Warrior
        [842] = false, --Ulbukan Stalwart
        [843] = false, --Toxin Tussler
        [844] = false, --SpiritualÅöStar
        [845] = false, --StipplingÅöStar
        [846] = true, --Geomancipator
        [847] = true, --Trialed-and-True Runeist
        [848] = true, --Queen's Confidante
        [849] = true, --Princess's Partisan
        [850] = true, --Potation Pathfinder
        [851] = true, --Storied Geomancer
        [852] = true, --Ultimate Runeist
        [853] = true, --Mog Garden Seedling
        [854] = true, --Kit Empathizer
        [855] = true, --Jingly Dangler
        [856] = true, --Mole Manipulator
        [857] = true, --Agrarian Novice
        [858] = true, --Agrarian Initiate
        [859] = true, --Agrarian Professional
        [860] = true, --Agrarian Virtuoso
        [861] = false, --Agrarian Tutelar
        [862] = true, --Weed Praetor
        [863] = true, --Tree Praetor
        [864] = true, --Thicket Praetor
        [865] = true, --Forest Praetor
        [866] = false, --Jungle Praetor
        [867] = true, --Copper Mattock
        [868] = true, --Silver Mattock
        [869] = true, --Mythril Mattock
        [870] = true, --Gold Mattock
        [871] = false, --Adamanttock
        [872] = true, --Puddle Patron
        [873] = true, --Swamp Savant
        [874] = false, --Pond Preceptor
        [875] = false, --River Regent
        [876] = false, --Monke-Onke Master
        [877] = true, --Sardineophyte
        [878] = true, --Calamareeler
        [879] = false, --Octopotentate
        [880] = false, --Giant Squimperator
        [881] = false, --Leviauthority
        [882] = true, --Novice Nurseryman
        [883] = true, --Lesser Landscaper
        [884] = true, --Greater Gardener
        [885] = false, --Honored Horticulturist
        [886] = false, --Mog Gardener
        [887] = true, --Brygidesque Manager
        [888] = true, --Vegetable Evolutionary
        [889] = false, --Blade Enthusiast
        [890] = false, --Runic Emissary
        [891] = false, --Maester of Maddening
        [892] = true, --Sunshine Cadet
        [893] = true, --Quartet Captivator
        [894] = true, --The Trustworthy
        [895] = true, --The Lovelorn
        [896] = true, --Inventor Extraordinaire
        [897] = true, --Boomy and Busty
        [898] = true, --Weatherer of Brumal Climes
        [899] = true, --White Knight
        [900] = true, --Light of Dawn
        [901] = false, --Observer of Fateful Cubes
        [902] = true, --Knower of Untruths
        [903] = true, --Ulbukan Understudy
        [904] = true, --Keeper of Ulbuka
        [905] = true, --Radiance of Daybreak
        [906] = true, --Wibbly Wobbly Woozy Warrior
        [907] = true, --Heir of Eternity
        [908] = true, --Prospective Pamperer
        [909] = true, --Novice Nuzzler
        [910] = true, --Serious Snuggler
        [911] = false, --Cultivated Coddler
        [912] = false, --Respected Ruffler
        [913] = true, --Dung Disseminator
        [914] = true, --Fauna Feeder
        [915] = false, --Confident Caretaker
        [916] = false, --Glorious Groomer
        [917] = false, --Transcendental Tamer
        [918] = true, --Bond-building Breeder
        [919] = false, --Clumsy Cleaver
        [920] = false, --Disciplined Dissector
        [921] = false, --Established Examiner
        [922] = true, --Sublime Slicer
        [923] = true, --Lifter of Spirits
        [924] = true, --Shedder of Harlequin Tears
        [925] = true, --Hope for the Future
        [926] = true, --Thousand-Year Traveler
        [927] = true, --Vanquisher of Ashrakk
        [928] = true, --Vanquisher of Dhokmak
        [929] = true, --Protected by Ulbukan Spirits
        [930] = true, --Receiver of Sigils
        [931] = true, --Destroyer of Hades
        [932] = true, --Bringer of the Dawn
        [933] = true, --The One True Pioneer
        [934] = true, --Bringer of Hope
        [935] = true, --Good Dew-er
        [936] = false, --Lifecycler
        [937] = false, --Sword Saint
        [938] = true, --The Fated
        [939] = true, --Protector of the Sacred City
        [940] = false, --Urmahlullu Usurper
        [941] = false, --Blazewing Berater
        [942] = false, --Coven Collapser
        [943] = false, --Pazuzu Perplexer
        [944] = false, --Wrathare Waxer
        [945] = false, --Lupine Liquidator
        [946] = false, --Ruby Repulser
        [947] = false, --Devil's Demise
        [948] = true, --Custodian of Ulbuka
        [949] = true, --Azi Dahaka Annihilator
        [950] = true, --Naga Raja Nullifier
        [951] = true, --Quetzalcoatl Plucker
        [952] = false, --Pakecet Pacifier
        [953] = false, --Duke Vepar Vanquisher
        [954] = false, --Vir'ava Vegetator
        [955] = false, --Byakko Tamer
        [956] = false, --Genbu Cracker
        [957] = false, --Seiryu Clipper
        [958] = false, --Suzaku Plucker
        [959] = false, --Kirin Dismantler
        [960] = false, --Vanquisher of Apathy
        [961] = false, --Vanquisher of Cowardice
        [962] = false, --Vanquisher of Envy
        [963] = false, --Vanquisher of Arrogance
        [964] = false, --Vanquisher of Rage
        [965] = false, --Purger of the Warder
        [966] = true, --Conquerer of Fear
        [967] = false, --Dawn's Delight
        [968] = false, --Maju Mauler
        [969] = false, --Yakshi Yanker
        [970] = false, --Neak Nullifier
        [971] = false, --Teles Terrifier
        [972] = true, --Assistant Extraordinaire
        [973] = false, --Exalted Fisherman
        [974] = true, --Sauce Supreme
        [975] = false, --Fish Whisperer
        [976] = true, --Abyssal Purveyor
        [977] = true, --Banisher of the Profane
        [978] = true, --Spirit Seeker
        [979] = true, --One-Eyed Jack
        [980] = false, --Curator Culler
        [981] = true, --Master Centurion
        [982] = false, --Master Brawler
        [983] = false, --Master Healer
        [984] = false, --Master Wizard
        [985] = false, --Master Warlock
        [986] = false, --Master Rogue
        [987] = false, --Master Templar
        [988] = false, --Master Soulstealer
        [989] = false, --Master Tamer
        [990] = false, --Master Lyricist
        [991] = false, --Master Hunter
        [992] = false, --Master Mononofu
        [993] = false, --Master Shinobi
        [994] = false, --Master Hussar
        [995] = false, --Master Evoker
        [996] = false, --Master Magus
        [997] = false, --Master Privateer
        [998] = false, --Master Puppeteer
        [999] = false, --Master Headliner
        [1000] = false, --Master Academic
        [1001] = false, --Master Naturalist
        [1002] = true, --Master Runeist
        [1003] = false, --Zerde Zapper
        [1004] = false, --Vinipata Vanquisher
        [1005] = false, --Schah Scraper
        [1006] = false, --Albumen Aggrivator
        [1007] = false, --Onychophora Obliterator
        [1008] = false, --Erinys Engulfer
        [1009] = false, --Herald of a New Age
        [1010] = false, --Preventer of the Second Coming
        [1011] = false, --Lux Ex Tenebris
        [1012] = false, --The Triumphant
        [1013] = true, --Fu Fighter
        [1014] = true, --Kyou Killer
        [1015] = true, --Kei Combuster
        [1016] = true, --Gin Gagger
        [1017] = true, --Kin Kicker
        [1018] = false, --Ou Obliterator
        [1019] = true, --Dynamis-San d'Oria [D] Trespasser
        [1020] = false, --Dynamis-San d'Oria [D] Infiltrator
        [1021] = false, --Dynamis-San d'Oria [D] Dominator
        [1022] = true, --Dynamis-Bastok [D] Trespasser
        [1023] = true, --Dynamis-Bastok [D] Infiltrator
        [1024] = true, --Dynamis-Bastok [D] Dominator
        [1025] = true, --Dynamis-Windurst [D] Trespasser
        [1026] = false, --Dynamis-Windurst [D] Infiltrator
        [1027] = false, --Dynamis-Windurst [D] Dominator
        [1028] = true, --Dynamis-Jeuno [D] Trespasser
        [1029] = true, --Dynamis-Jeuno [D] Infiltrator
        [1030] = false, --Dynamis-Jeuno [D] Dominator
        [1031] = false, --Mimic Masher
        [1032] = false, --Judge, Jury, and Executioner
        [1033] = false, --Zeroine to Heroine
        [1034] = false, --Every Ilm a Heroine
        [1035] = true, --Dread Purger
        [1036] = false, --Sidhe Smasher
        [1037] = false, --Alexander Annihilator
        [1038] = false, --Lilith Liquidator
        [1039] = true, --Mireu Mincer
        [1040] = false, --Draconic Interloper
        [1044] = true, --Vegetable Hero
        [1045] = true, --Contributer from the Shadows
        [1046] = true, --The Decider
        [1047] = true, --The Ascended
        [1048] = true, --The Savior of Vana'diel
        [1049] = true, --Blessed by the Avatars
        [1050] = true, --Seer of Songs
        [1051] = false, --The Eternal Wind
        [1052] = false, --Dealan-dhe Dimmer
        [1053] = false, --Sgili Stomper
        [1054] = false, --U Bnai Underminer
        [1055] = true, --Gogmagog Grinder
        [1056] = false, --Aristaeus Assailer
        [1057] = false, --Marmorkrebs Mauler
        [1058] = true, --Gigelorum Gagger
        [1059] = false, --Raskovniche Render
        [1060] = false, --Procne Punisher
        [1061] = false, --Henwen Harrier
        [1062] = false, --Xevioso Zapper
        [1063] = false, --Ngai Nabber
        [1064] = true, --Kalunga Collapser
        [1065] = false, --Mboze Mauler
        [1066] = true, --Ongo Obliterator
        [1067] = false, --Arebati Assaulter
        [1068] = true, --Bumba Befouler
        [1069] = true, --Dhartok Defiler
        [1070] = false, --Gartell Grinder
        [1071] = true, --Triboulex Terrorizer
        [1072] = false, --Aita Abnegater
        [1073] = false, --Aminon Apprehender
        [1074] = false, --Paradise Regained
        [1075] = false, --Founder's Pride
        [1076] = false, --Master of All
        [1077] = false, --Eternal Master
        [1116] = false, --Raptor Wrangler
        [1117] = true, --Gardener for the Ages
        [1118] = true, --Lagoon Explorer
        [1119] = true, --Servant to the Servant
        [1120] = false, --Legendary Woodworker
        [1121] = false, --Legendary Blacksmith
        [1122] = false, --Legendary Goldsmith
        [1123] = false, --Legendary Weaver
        [1124] = false, --Legendary Tanner
        [1125] = false, --Legendary Boneworker
        [1126] = false, --Legendary Alchemist
        [1127] = false, --Legendary Culinarian
        [1128] = false, --Eternal Communer
        [1129] = true, --Destiny Destroyer...Destroyer
        [1130] = true, --Fully-Baked Hero
        [1131] = true, --Ghdwk Vshdnhu
        [1132] = true, --Love is Alive
        [1133] = true, --The Awakener
        [1134] = true, --Get Over Here!
        [1135] = true, --Bond Renewer
        [1136] = true, --Treasure of Olduum
        [1137] = true, --Beloved by the Sea God
        [1138] = true, --Destiny Master
        [1139] = true, --Tireless Tracker
        [1140] = true, --Galkan Hazard
        [1141] = true, --Bearer of Secrets
        [1142] = true, --Long Live Mumor
        [1143] = true, --Parter of the Veil
        [1144] = true, --Demonic Dreamer
        [1145] = true, --Searcher of the Voracious
        [1146] = true, --Another Psyche
        [1147] = true, --Sender of Shadow
        [1148] = true, --Astral Aligner
        [1149] = false, --Venerated Adventurer
    },
};