return T{
    ["LTRT:5"] = {
        ActionType              = 'Trust',
        Id                      = 993,
        Macro                   = T{
            "/ma \"Monberaux\" <me> <wait 7>",
            "/ma \"Koru-moru\" <me> <wait 7>",
            "/ma \"Selh'teus\" <me> <wait 7>",
            "/ma \"Shantotto II\" <me> <wait 7>",
            "/ma \"Ulmia\" <me>",
        },
        Label                   = "Tank Trusts",
        Image                   = "spells/993.png",
        ShowCost                = true,
        ShowCross               = false,
        ShowFade                = true,
        ShowRecast              = true,
        ShowName                = true,
        ShowTrigger             = true,
        ShowSkillchainIcon      = true,
        ShowSkillchainAnimation = true,
        ShowHotkey              = false,
    },
    ["LTRT:7"] = {
        ActionType              = 'Trust',
        Id                      = 993,
        Macro                   = T{
            "/ma \"Monberaux\" <me> <wait 7>",
            "/ma \"Koru-moru\" <me> <wait 7>",
            "/ma \"Ygnas\" <me> <wait 7>",
            "/ma \"Joachim\" <me> <wait 7>",
            "/ma \"Ulmia\" <me>",
        },
        Label                   = "DPS Trusts",
        Image                   = "spells/993.png",
        ShowCost                = true,
        ShowCross               = true,
        ShowFade                = true,
        ShowRecast              = true,
        ShowName                = true,
        ShowTrigger             = true,
        ShowSkillchainIcon      = true,
        ShowSkillchainAnimation = true,
        ShowHotkey              = false,
    },
    ["LTRT:6"] = {
        ActionType              = 'Trust',
        Id                      = 993,
        Macro                   = T{
            "/ma \"Valaineral\" <me> <wait 7>",
            "/ma \"Lion II\" <me> <wait 7>",
            "/ma \"Monberaux\" <me> <wait 7>",
            "/ma \"Koru-moru\" <me> <wait 7>",
            "/ma \"Semih Lafihna\" <me>",
        },
        Label                   = "AOE Trusts",
        Image                   = "spells/993.png",
        ShowCost                = true,
        ShowCross               = true,
        ShowFade                = true,
        ShowRecast              = true,
        ShowName                = true,
        ShowTrigger             = true,
        ShowSkillchainIcon      = true,
        ShowSkillchainAnimation = true,
        ShowHotkey              = false,
    },
    ["LTRT:8"] = {
        ActionType              = 'Trust',
        Id                      = 993,
        Macro                   = T{
            "/ma \"Monberaux\" <me> <wait 7>",
            "/ma \"Koru-moru\" <me> <wait 7>",
            "/ma \"August\" <me> <wait 7>",
            "/ma \"Shantotto II\" <me> <wait 7>",
            "/ma \"Zeid II\" <me>",
        },
        Label                   = "Support Trusts",
        Image                   = "spells/993.png",
        ShowCost                = true,
        ShowCross               = true,
        ShowFade                = true,
        ShowRecast              = true,
        ShowName                = true,
        ShowTrigger             = true,
        ShowSkillchainIcon      = true,
        ShowSkillchainAnimation = true,
        ShowHotkey              = false,
    },
};