return T{
    Default = T{
    },
    Palettes = T{
        { Name="Base", Bindings = T{
            ["LT:7"] = {
                ActionType              = 'Ability',
                Id                      = 881,
                Macro                   = T{
                    "/ja \"Pflug\" <me>",
                },
                Label                   = "Pflug",
                Image                   = "abilities/369.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:1"] = {
                ActionType              = 'Ability',
                Id                      = 883,
                Macro                   = T{
                    "/ja \"Valiance\" <me>",
                },
                Label                   = "Valiance",
                Image                   = "abilities/371.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:3"] = {
                ActionType              = 'Ability',
                Id                      = 885,
                Macro                   = T{
                    "/ja \"Liement\" <me>",
                },
                Label                   = "Liement",
                Image                   = "abilities/373.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:5"] = {
                ActionType              = 'Ability',
                Id                      = 874,
                Macro                   = T{
                    "/ja \"Sulpor\" <me>",
                },
                Label                   = "Thunder",
                Image                   = "abilities/362.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:3"] = {
                ActionType              = 'Ability',
                Id                      = 872,
                Macro                   = T{
                    "/ja \"Flabra\" <me>",
                },
                Label                   = "Wind",
                Image                   = "abilities/360.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:8"] = {
                ActionType              = 'Ability',
                Id                      = 563,
                Macro                   = T{
                    "/ja \"Last Resort\" <me>",
                },
                Label                   = "Last Resort",
                Image                   = "abilities/51.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:1"] = {
                ActionType              = 'Ability',
                Id                      = 870,
                Macro                   = T{
                    "/ja \"Ignis\" <me>",
                },
                Label                   = "Fire",
                Image                   = "abilities/358.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:6"] = {
                ActionType              = 'Weaponskill',
                Id                      = 61,
                Macro                   = T{
                    "/ws \"Dimidiation\" <t>",
                },
                Label                   = "Dimidiation",
                Image                   = "ITEM:20753",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:8"] = {
                ActionType              = 'Weaponskill',
                Id                      = 52,
                Macro                   = T{
                    "/ws \"Shockwave\" <t>",
                },
                Label                   = "Shockwave",
                Image                   = "ITEM:16942",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:5"] = {
                ActionType              = 'Command',
                Macro                   = T{
                    "/attack <t>",
                },
                Label                   = "Attack",
                Image                   = "misc/command.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:4"] = {
                ActionType              = 'Spell',
                Id                      = 476,
                Macro                   = T{
                    "/ma \"Crusade\" <me>",
                },
                Label                   = "Crusade",
                Image                   = "spells/476.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:1"] = {
                ActionType              = 'Spell',
                Id                      = 112,
                Macro                   = T{
                    "/ma \"Flash\" <t>",
                },
                Label                   = "Flash",
                Image                   = "spells/112.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:3"] = {
                ActionType              = 'Spell',
                Id                      = 252,
                Macro                   = T{
                    "/ma \"Stun\" <t>",
                },
                Label                   = "Stun",
                Image                   = "spells/252.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:6"] = {
                ActionType              = 'Ability',
                Id                      = 875,
                Macro                   = T{
                    "/ja \"Unda\" <me>",
                },
                Label                   = "Water",
                Image                   = "abilities/363.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LTRT:7"] = {
                ActionType              = 'Ability',
                Id                      = 562,
                Macro                   = T{
                    "/ma \"Monberaux\" <me> <wait 7>",
                    "/ma \"Koru-moru\" <me> <wait 7>",
                    "/ma \"Ygnas\" <me> <wait 7>",
                    "/ma \"Joachim\" <me> <wait 7>",
                    "/ma \"Ulmia\" <me>",
                },
                Label                   = "DPS Trusts",
                Image                   = "abilities/50.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:6"] = {
                ActionType              = 'Ability',
                Id                      = 879,
                Macro                   = T{
                    "/ja \"Swordplay\" <me>",
                },
                Label                   = "Swordplay",
                Image                   = "abilities/367.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LTRT:6"] = {
                ActionType              = 'Ability',
                Id                      = 562,
                Macro                   = T{
                    "/ma \"Valaineral\" <me> <wait 7>",
                    "/ma \"Lion II\" <me> <wait 7>",
                    "/ma \"Monberaux\" <me> <wait 7>",
                    "/ma \"Koru-moru\" <me> <wait 7>",
                    "/ma \"Semih Lafihna\" <me>",
                },
                Label                   = "AOE Trusts",
                Image                   = "abilities/50.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:2"] = {
                ActionType              = 'Ability',
                Id                      = 878,
                Macro                   = T{
                    "/ja \"Vallation\" <me>",
                },
                Label                   = "Vallation",
                Image                   = "abilities/366.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:4"] = {
                ActionType              = 'Ability',
                Id                      = 888,
                Macro                   = T{
                    "/ja \"Battuta\" <me>",
                },
                Label                   = "Battuta",
                Image                   = "abilities/376.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:7"] = {
                ActionType              = 'Weaponskill',
                Id                      = 60,
                Macro                   = T{
                    "/ws \"Resolution\" <t>",
                },
                Label                   = "Resolution",
                Image                   = "ITEM:21694",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:2"] = {
                ActionType              = 'Ability',
                Id                      = 871,
                Macro                   = T{
                    "/ja \"Gelus\" <me>",
                },
                Label                   = "Ice",
                Image                   = "abilities/359.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RT:2"] = {
                ActionType              = 'Spell',
                Id                      = 840,
                Macro                   = T{
                    "/ma \"Foil\" <me>",
                },
                Label                   = "Foil",
                Image                   = "spells/840.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:7"] = {
                ActionType              = 'Ability',
                Id                      = 876,
                Macro                   = T{
                    "/ja \"Lux\" <me>",
                },
                Label                   = "Light",
                Image                   = "abilities/364.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:4"] = {
                ActionType              = 'Ability',
                Id                      = 873,
                Macro                   = T{
                    "/ja \"Tellus\" <me>",
                },
                Label                   = "Earth",
                Image                   = "abilities/361.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["RTLT:8"] = {
                ActionType              = 'Ability',
                Id                      = 877,
                Macro                   = T{
                    "/ja \"Tenebrae\" <me>",
                },
                Label                   = "Dark",
                Image                   = "abilities/365.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
            ["LT:5"] = {
                ActionType              = 'Ability',
                Id                      = 882,
                Macro                   = T{
                    "/ja \"Embolden\" <me>",
                },
                Label                   = "Embolden",
                Image                   = "abilities/370.png",
                ShowCost                = true,
                ShowCross               = true,
                ShowFade                = true,
                ShowRecast              = true,
                ShowName                = true,
                ShowTrigger             = true,
                ShowSkillchainIcon      = true,
                ShowSkillchainAnimation = true,
                ShowHotkey              = false,
            },
        } },
    },
};